[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
qal_anchor = "6cN9gD8LBqkEUhvT4LibnbBgXdCHeC5AgqvcFQQTNvnR"

[programs.devnet]
qal_anchor = "6cN9gD8LBqkEUhvT4LibnbBgXdCHeC5AgqvcFQQTNvnR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p qal-anchor"

[hooks]
